/**
 * Curated reveal soundtrack registry. Files live in /public/music and are
 * placeholder synth beds generated by scripts/gen-music.mjs — swap each .wav
 * for the licensed track of the same id before launch. Track ids are what get
 * persisted, so replacing audio files never touches data.
 */
export interface MusicTrack {
  id: string;
  name: string;
  description: string;
  file: string;
}

export const MUSIC_TRACKS: MusicTrack[] = [
  { id: "warm-keys", name: "Warm keys", description: "Soft piano, unhurried", file: "/music/warm-keys.wav" },
  { id: "paper-lanterns", name: "Paper lanterns", description: "Plucked, festive, light", file: "/music/paper-lanterns.wav" },
  { id: "slow-waltz", name: "Slow waltz", description: "Three-four, close and warm", file: "/music/slow-waltz.wav" },
  { id: "golden-hour", name: "Golden hour", description: "Hazy chords, late light", file: "/music/golden-hour.wav" },
];

export function getTrackById(id: string | null | undefined): MusicTrack | null {
  if (!id) return null;
  return MUSIC_TRACKS.find((t) => t.id === id) ?? null;
}
