import { NextRequest, NextResponse } from "next/server";
import { stripe } from "@/lib/stripe";
import { createAdminClient } from "@/lib/supabase/server";
import Stripe from "stripe";
import { sendEmail } from "@/lib/email/send";
import { giftInviteEmail } from "@/lib/email/templates";
import { logAudit } from "@/lib/audit";
import { APP_URL } from "@/lib/constants";

export async function POST(request: NextRequest) {
  const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET;
  if (!webhookSecret) {
    console.error("[stripe] STRIPE_WEBHOOK_SECRET not configured");
    return NextResponse.json({ error: "Server misconfigured" }, { status: 500 });
  }

  const body = await request.text();
  const signature = request.headers.get("stripe-signature");

  if (!signature) {
    return NextResponse.json({ error: "No signature" }, { status: 400 });
  }

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(body, signature, webhookSecret);
  } catch (err) {
    console.error("Webhook signature verification failed:", err);
    return NextResponse.json({ error: "Invalid signature" }, { status: 400 });
  }

  const supabase = createAdminClient();

  // Idempotency via claim_stripe_event for all non-gift events.
  // The gift branch has its own dedup (stripe_session_id UNIQUE on gift_purchases)
  // so that a DB insert failure can return 500 and Stripe can retry successfully.
  const isGiftEvent =
    event.type === "checkout.session.completed" &&
    (event.data.object as Stripe.Checkout.Session).metadata?.mode === "gift";

  if (!isGiftEvent) {
    const { data: claimed } = await supabase.rpc("claim_stripe_event", {
      p_event_id: event.id,
      p_event_type: event.type,
    });
    if (claimed === false) {
      return NextResponse.json({ received: true, duplicate: true });
    }
  }

  // One-time payment (Plus per-invite)
  if (event.type === "checkout.session.completed") {
    const session = event.data.object as Stripe.Checkout.Session;
    const userId = session.metadata?.user_id;
    const themeId = session.metadata?.theme_id;
    const subscriptionType = session.metadata?.subscription_type;
    // Gift sessions use metadata.mode = "gift" (no user_id in metadata)
    const sessionMode = session.metadata?.mode;
    const customerId =
      typeof session.customer === "string" ? session.customer : session.customer?.id ?? null;

    // ── Gift payment ────────────────────────────────────────────────────────
    // Dedup for gift branch: use the stripe_session_id UNIQUE constraint on
    // gift_purchases rather than claim_stripe_event. This way a DB insert
    // failure returns 500 → Stripe retries, and the retry can still insert
    // (claim_stripe_event would have blocked it on retry).
    if (sessionMode === "gift" && session.payment_status === "paid") {
      const recipientEmail = session.metadata?.gift_recipient_email;
      const giftMessage = session.metadata?.gift_message ?? null;
      const giftSenderName = session.metadata?.gift_sender_name ?? null;
      const senderEmail = session.metadata?.sender_email ?? null;

      if (recipientEmail) {
        // Insert gift_purchases row (redeem_token auto-generated by DB).
        // ON CONFLICT DO NOTHING on stripe_session_id handles duplicate deliveries.
        const { data: giftRow, error: insertError } = await supabase
          .from("gift_purchases")
          .insert({
            stripe_session_id: session.id,
            sender_email: senderEmail,
            sender_name: giftSenderName,
            recipient_email: recipientEmail,
            gift_message: giftMessage,
          })
          .select("redeem_token, id")
          .maybeSingle();

        if (insertError) {
          // Real DB error — return 500 so Stripe retries. The unique constraint
          // on stripe_session_id prevents double-inserts on retry.
          console.error("[gift] Failed to insert gift_purchases:", insertError.message);
          return NextResponse.json({ error: "DB error" }, { status: 500 });
        }

        if (giftRow) {
          // Row was newly inserted — send email and audit log.
          const redeemUrl = `${APP_URL}/gift/redeem?token=${giftRow.redeem_token}`;
          const emailPayload = giftInviteEmail({
            recipientEmail,
            redeemUrl,
            senderName: giftSenderName ?? undefined,
            giftMessage: giftMessage ?? undefined,
          });

          const emailResult = await sendEmail(recipientEmail, emailPayload.subject, emailPayload.html);
          if (!emailResult.success) {
            // Log but do NOT fail the webhook — row is safe, email can be retried separately.
            console.error("[gift] Failed to send gift email:", emailResult.error);
          }

          // Audit log: fire-and-forget. Log domain only, not full email (PII).
          void logAudit({
            userId: null,
            action: "gift.sent",
            meta: { gift_id: giftRow.id, recipient_domain: recipientEmail.split("@")[1] },
          });
        }
        // If giftRow is null, stripe_session_id already existed → duplicate delivery, 200 OK.
      }

      return NextResponse.json({ received: true });
    }

    if (userId && session.payment_status === "paid") {
      // Verify the user_id in metadata matches the bound stripe customer id.
      // First payment for a user binds the customer; subsequent payments must match.
      if (customerId) {
        const { data: ok } = await supabase.rpc("verify_stripe_customer", {
          p_user_id: userId,
          p_customer_id: customerId,
        });
        if (ok !== true) {
          console.error(`[stripe] customer/user mismatch on session ${session.id}`);
          return NextResponse.json({ error: "Customer/user mismatch" }, { status: 400 });
        }
      }

      if (subscriptionType === "plus" && themeId) {
        // Match on the pre-stamped session id only. createInviteShell writes
        // stripe_session_id at publish time after verifying the session with
        // Stripe, so the correct invite is always identifiable this way.
        //
        // The old "else most recent unpaid invite with this theme" fallback is
        // deliberately gone: it consumed the session against an unrelated,
        // pre-existing draft, after which the buyer's real publish hit the
        // anti-replay guard and could never spend the purchase.
        const { data: existing } = await supabase
          .from("invites")
          .select("id")
          .eq("stripe_session_id", session.id)
          .limit(1)
          .maybeSingle();

        if (existing?.id) {
          await supabase
            .from("invites")
            .update({ is_paid: true })
            .eq("id", existing.id);
        } else {
          // Normal race: payment settled before the user finished publishing.
          // createInviteShell stamps is_paid itself, so nothing is lost.
          console.warn(
            `[stripe] paid session ${session.id} has no invite yet — publish will claim it`
          );
        }
      }
    }
  }

  // Subscription created or renewed
  if (
    event.type === "customer.subscription.created" ||
    event.type === "customer.subscription.updated"
  ) {
    const subscription = event.data.object as Stripe.Subscription;
    const userId = subscription.metadata?.user_id;
    const customerId =
      typeof subscription.customer === "string"
        ? subscription.customer
        : subscription.customer?.id ?? null;

    if (userId && customerId) {
      const { data: ok } = await supabase.rpc("verify_stripe_customer", {
        p_user_id: userId,
        p_customer_id: customerId,
      });
      if (ok !== true) {
        console.error(`[stripe] customer/user mismatch on sub ${subscription.id}`);
        return NextResponse.json({ error: "Customer/user mismatch" }, { status: 400 });
      }

      const isActive = subscription.status === "active" || subscription.status === "trialing";
      const periodEnd = (subscription as unknown as { current_period_end?: number })
        .current_period_end;
      const expiresAt =
        isActive && typeof periodEnd === "number"
          ? new Date(periodEnd * 1000).toISOString()
          : null;

      await supabase.from("profiles").upsert({
        id: userId,
        subscription_tier: isActive ? "unlimited" : "free",
        subscription_expires_at: expiresAt,
      });
    }
  }

  // Subscription cancelled / expired
  if (event.type === "customer.subscription.deleted") {
    const subscription = event.data.object as Stripe.Subscription;
    const userId = subscription.metadata?.user_id;
    const customerId =
      typeof subscription.customer === "string"
        ? subscription.customer
        : subscription.customer?.id ?? null;

    if (userId && customerId) {
      const { data: ok } = await supabase.rpc("verify_stripe_customer", {
        p_user_id: userId,
        p_customer_id: customerId,
      });
      if (ok !== true) {
        console.error(`[stripe] customer/user mismatch on sub.deleted ${subscription.id}`);
        return NextResponse.json({ error: "Customer/user mismatch" }, { status: 400 });
      }

      await supabase.from("profiles").upsert({
        id: userId,
        subscription_tier: "free",
        subscription_expires_at: null,
      });
    }
  }

  return NextResponse.json({ received: true });
}
