/**
 * ScrollStoryReveal — native port of the web "scroll_story" reveal grammar.
 * One long vertical Animated.ScrollView with 6 scenes stacked in a seamless
 * day → night gradient handoff (SkyHero → Message → Plan → Polaroid → Rsvp →
 * Finale). Not a copy of the web DOM — this is RN: gradients are
 * `expo-linear-gradient` layers, parallax runs on Reanimated 4 shared values
 * on the UI thread, and scene entry ticks a light haptic instead of firing a
 * DOM IntersectionObserver.
 *
 * MUSIC PARITY: the web reveal has a tap-gated chime toggle; this ports it with
 * `expo-audio` (bundled with SDK 54). A locally-synthesized ~2.5s Cmaj7 arpeggio
 * (assets/audio/chime.wav, generated by scripts/gen-chime.js) loops ONLY after
 * the user taps the top-right toggle — never on autoplay, per browser/mobile
 * audio-policy convention. `useAudioPlayer` releases the player on unmount, so
 * playback stops when the reveal is torn down. Audio is intentionally NOT gated
 * by reduced-motion: reduced-motion suppresses vestibular-triggering movement,
 * not sound the user explicitly opted into.
 */
import { useCallback, useEffect, useRef, useState } from "react";
import { AccessibilityInfo, Pressable, Text, View, useWindowDimensions } from "react-native";
import Animated, { useAnimatedScrollHandler, useSharedValue } from "react-native-reanimated";
import * as Haptics from "expo-haptics";
import { useAudioPlayer, setAudioModeAsync } from "expo-audio";
import type { StoryConfig } from "@/lib/scroll-story/config";
import SkyHero from "./SkyHero";
import MessageScene from "./MessageScene";
import PlanScene from "./PlanScene";
import PolaroidScene from "./PolaroidScene";
import RsvpScene from "./RsvpScene";
import FinaleScene from "./FinaleScene";
import { FINALE_NIGHT } from "./shared";
import ReactionBar from "@/components/reveal/ReactionBar";

const CHIME_SOURCE = require("../../../../assets/audio/chime.wav");

interface ScrollStoryRevealProps {
  config: StoryConfig;
  /** Real invite id — when present the RSVP scene records to Supabase. */
  inviteId?: string;
  /**
   * C6 renders this against an unpublished draft. RSVPs already no-op without
   * an `inviteId`; this additionally hides the reaction bar, because a reaction
   * is keyed by SLUG and the draft slug becomes real at publish — a tap in a
   * preview would pre-seed a reaction on a surprise nobody has seen yet.
   */
  preview?: boolean;
  /** Slug drives the reaction bar; absent on the demo config. */
  slug?: string;
  /** Forwarded so a PIN-locked surprise still accepts a reaction. */
  pin?: string | null;
}

const HERO_HEIGHT_FACTOR = 1.75;
const HAPTIC_SCENE_COUNT = 6;

export default function ScrollStoryReveal({
  config,
  inviteId,
  preview = false,
  slug,
  pin = null,
}: ScrollStoryRevealProps) {
  const { height: windowHeight } = useWindowDimensions();
  const [reduced, setReduced] = useState(false);
  const [musicOn, setMusicOn] = useState(false);
  const scrollY = useSharedValue(0);
  const lastHapticScene = useRef(-1);

  // Looping chime — loaded but silent until the user taps the toggle. The hook
  // auto-releases the player on unmount, so nothing keeps playing after the
  // reveal closes.
  const player = useAudioPlayer(CHIME_SOURCE);

  useEffect(() => {
    AccessibilityInfo.isReduceMotionEnabled().then(setReduced);
  }, []);

  useEffect(() => {
    player.loop = true;
    // Play through the iOS hardware silent switch — this is opt-in audio.
    setAudioModeAsync({ playsInSilentMode: true }).catch(() => {});
  }, [player]);

  const toggleMusic = useCallback(() => {
    setMusicOn((on) => {
      const next = !on;
      try {
        if (next) {
          player.seekTo(0);
          player.play();
        } else {
          player.pause();
        }
      } catch {
        // Player may not be loaded yet on the very first tap; ignore and let
        // the next tap take effect once the source is ready.
      }
      return next;
    });
  }, [player]);

  // Rough per-scene boundary in px, used only to throttle haptic scene-entry
  // ticks — not for layout. Scene 1 is 1.75x window height; every scene after
  // that is treated as one more window-height "page" for haptic purposes.
  const sceneBoundaries = useRef(
    Array.from({ length: HAPTIC_SCENE_COUNT }, (_, i) =>
      i === 0 ? 0 : windowHeight * HERO_HEIGHT_FACTOR + (i - 1) * windowHeight * 0.6
    )
  ).current;

  const triggerSceneHaptic = useCallback(
    (sceneIndex: number) => {
      if (reduced) return;
      if (lastHapticScene.current === sceneIndex) return;
      lastHapticScene.current = sceneIndex;
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(() => {});
    },
    [reduced]
  );

  /**
   * D2: "Scenes are full-height snap sections (`snapToInterval`,
   * `decelerationRate: 'fast'`)."
   *
   * `sceneBoundaries` above is explicitly NOT layout — it is an approximation
   * for haptic thresholds, and snapping to it would stop the scroll in the
   * middle of scenes. The real offsets are measured instead, so snapping lands
   * on the seams the scenes actually have. Until every scene has reported, the
   * list is empty and the ScrollView simply does not snap — which is the right
   * failure: a wrong snap point is worse than none.
   */
  const [snapOffsets, setSnapOffsets] = useState<number[]>([]);
  const measured = useRef<number[]>([]);
  const onSceneLayout = useCallback((index: number, y: number) => {
    measured.current[index] = y;
    if (measured.current.filter((v) => typeof v === "number").length === HAPTIC_SCENE_COUNT) {
      setSnapOffsets([...measured.current]);
    }
  }, []);

  const scrollHandler = useAnimatedScrollHandler({
    onScroll: (event) => {
      "worklet";
      scrollY.value = event.contentOffset.y;
    },
  });

  // JS-thread scroll listener purely for haptic scene-entry thresholds — kept
  // separate from the UI-thread worklet above so haptics (a JS/native-module
  // call) never run on the UI thread.
  const handleJsScroll = useCallback(
    (event: { nativeEvent: { contentOffset: { y: number } } }) => {
      const y = event.nativeEvent.contentOffset.y;
      let currentScene = 0;
      for (let i = sceneBoundaries.length - 1; i >= 0; i--) {
        if (y >= sceneBoundaries[i] - windowHeight * 0.3) {
          currentScene = i;
          break;
        }
      }
      triggerSceneHaptic(currentScene);
    },
    [sceneBoundaries, triggerSceneHaptic, windowHeight]
  );

  return (
    <>
      <Animated.ScrollView
        onScroll={(event) => {
          scrollHandler(event);
          handleJsScroll(event);
        }}
        scrollEventThrottle={16}
        showsVerticalScrollIndicator={false}
        snapToOffsets={snapOffsets.length === HAPTIC_SCENE_COUNT ? snapOffsets : undefined}
        decelerationRate="fast"
        // A scene taller than the viewport must stay scrollable rather than
        // being yanked to the next seam mid-read.
        disableIntervalMomentum
        style={{ flex: 1, backgroundColor: FINALE_NIGHT }}
      >
        <View onLayout={(e) => onSceneLayout(0, e.nativeEvent.layout.y)}>
          <SkyHero config={config} scrollY={scrollY} reduced={reduced} />
        </View>
        <View onLayout={(e) => onSceneLayout(1, e.nativeEvent.layout.y)}>
          <MessageScene config={config} reduced={reduced} />
        </View>
        <View onLayout={(e) => onSceneLayout(2, e.nativeEvent.layout.y)}>
          <PlanScene config={config} />
        </View>
        <View onLayout={(e) => onSceneLayout(3, e.nativeEvent.layout.y)}>
          <PolaroidScene config={config} />
        </View>
        <View onLayout={(e) => onSceneLayout(4, e.nativeEvent.layout.y)}>
          <RsvpScene config={config} inviteId={inviteId} reduced={reduced} />
        </View>
        <View onLayout={(e) => onSceneLayout(5, e.nativeEvent.layout.y)}>
          <FinaleScene config={config} reduced={reduced} />
        </View>
      </Animated.ScrollView>

      {/* D2's pinned reaction bar. Only with a real slug — the demo config has
          nothing to record against, and a bar whose counts never move is worse
          than no bar. */}
      {slug ? (
        <View style={{ position: "absolute", left: 20, bottom: 24 }}>
          {preview ? null : <ReactionBar slug={slug} pin={pin} reduced={reduced} />}
        </View>
      ) : null}

      <Pressable
        onPress={toggleMusic}
        accessibilityRole="button"
        accessibilityLabel={musicOn ? "Pause music" : "Play music"}
        // RN's AccessibilityState has no `pressed` (that's web ARIA); `selected`
        // is the RN-native way to expose a toggle's on/off state to a11y APIs.
        accessibilityState={{ selected: musicOn }}
        hitSlop={12}
        style={({ pressed }) => ({
          position: "absolute",
          top: 52,
          right: 20,
          width: 44,
          height: 44,
          borderRadius: 22,
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: "rgba(24,21,19,0.55)",
          borderWidth: 1,
          borderColor: "rgba(255,255,255,0.25)",
          transform: [{ scale: pressed ? 0.92 : 1 }],
        })}
      >
        <Text style={{ fontSize: 15, color: "#FFFEFD" }}>{musicOn ? "❚❚" : "♪"}</Text>
      </Pressable>
    </>
  );
}
